{% set name = "geobuf" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 96a347cd8443cc53a65f34f958b45b0e45c4cca8f1ca3b72078a3aec97605a72

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - geobuf = geobuf.scripts.cli:cli

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - click
    - protobuf
    - python >={{ python_min }}
    - six

test:
  imports:
    - geobuf
    - geobuf.scripts
  commands:
    - pip check
    - geobuf --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mapbox/pygeobuf
  summary: Geobuf is a compact binary geospatial format for lossless compression of GeoJSON and TopoJSON data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
